version: '3.7'
services:
  app:
    env_file:
      - ./config/docker-test.env
  e2e:
    build:
      dockerfile: Dockerfile.dev
      context: ./e2e
    container_name: cypress
    depends_on:
      - app
    env_file:
      - ./config/docker-test.env
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json
